// <auto-generated />
using System;
using CoffeeMate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeMate.Infrastructure.Migrations
{
    [DbContext(typeof(BaristaContext))]
    [Migration("20260415110010_RemoveRowVersion")]
    partial class RemoveRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coffees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Description = "A concentrated coffee brewed by forcing hot water under pressure through finely-ground beans. Bold, rich, and the foundation of most coffee drinks.",
                            Name = "Espresso",
                            Origin = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Description = "Espresso combined with steamed milk and a thin layer of foam. Smooth, creamy, and perfect for those who enjoy a milder coffee flavor.",
                            Name = "Latte",
                            Origin = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Description = "Equal parts espresso, steamed milk, and milk foam. A well-balanced drink with a velvety texture and strong coffee presence.",
                            Name = "Cappuccino",
                            Origin = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            Description = "Espresso diluted with hot water, producing a coffee similar in strength to drip brew but with a distinctly different flavor profile.",
                            Name = "Americano",
                            Origin = "United States"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            Description = "A chocolate-flavored variant of the latte, combining espresso, steamed milk, and chocolate syrup topped with whipped cream.",
                            Name = "Mocha",
                            Origin = "Yemen"
                        });
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestTokenId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.GuestToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("GuestTokens");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoffeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeId")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            CoffeeId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Description = "A single shot of pure espresso.",
                            Title = "Classic Espresso"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            CoffeeId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Description = "Smooth espresso with steamed milk and light foam.",
                            Title = "Classic Latte"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000003"),
                            CoffeeId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Description = "Balanced espresso with equal parts steamed milk and foam.",
                            Title = "Classic Cappuccino"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000004"),
                            CoffeeId = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            Description = "Espresso lengthened with hot water.",
                            Title = "Classic Americano"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000005"),
                            CoffeeId = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            Description = "Chocolate espresso drink topped with whipped cream.",
                            Title = "Classic Mocha"
                        });
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoffeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.SessionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionSteps");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0001-0001-000000000001"),
                            Description = "Grind 18g of coffee beans to a fine consistency.",
                            DurationSeconds = 30,
                            Name = "Grind Beans",
                            Order = 1,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0001-0001-000000000002"),
                            Description = "Distribute and tamp the grounds evenly in the portafilter with ~30 lbs of pressure.",
                            DurationSeconds = 15,
                            Name = "Tamp Grounds",
                            Order = 2,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0001-0001-000000000003"),
                            Description = "Lock the portafilter and extract for 25-30 seconds until you get ~36ml of espresso.",
                            DurationSeconds = 30,
                            Name = "Pull Shot",
                            Order = 3,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0001-0001-000000000004"),
                            Description = "Pour the espresso into a pre-warmed demitasse cup and serve immediately.",
                            DurationSeconds = 10,
                            Name = "Serve",
                            Order = 4,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0002-0001-000000000001"),
                            Description = "Grind 18g of coffee beans to a fine consistency.",
                            DurationSeconds = 30,
                            Name = "Grind Beans",
                            Order = 1,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0002-0001-000000000002"),
                            Description = "Extract a double shot of espresso (~36ml) into your cup.",
                            DurationSeconds = 30,
                            Name = "Pull Espresso Shot",
                            Order = 2,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0002-0001-000000000003"),
                            Description = "Steam 240ml of milk to 65°C with a thin layer of microfoam.",
                            DurationSeconds = 45,
                            Name = "Steam Milk",
                            Order = 3,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0002-0001-000000000004"),
                            Description = "Pour the steamed milk over the espresso in a steady stream, finishing with a thin foam layer.",
                            DurationSeconds = 15,
                            Name = "Pour Milk",
                            Order = 4,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0002-0001-000000000005"),
                            Description = "Serve immediately in a large cup or glass.",
                            DurationSeconds = 10,
                            Name = "Serve",
                            Order = 5,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0001-000000000001"),
                            Description = "Grind 18g of coffee beans to a fine consistency.",
                            DurationSeconds = 30,
                            Name = "Grind Beans",
                            Order = 1,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0001-000000000002"),
                            Description = "Extract a double shot of espresso (~36ml) into a cappuccino cup.",
                            DurationSeconds = 30,
                            Name = "Pull Espresso Shot",
                            Order = 2,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0001-000000000003"),
                            Description = "Steam 120ml of milk to 65°C, creating a thick and airy foam (more foam than a latte).",
                            DurationSeconds = 45,
                            Name = "Steam & Froth Milk",
                            Order = 3,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0001-000000000004"),
                            Description = "Pour steamed milk into the espresso, then spoon the thick foam on top.",
                            DurationSeconds = 20,
                            Name = "Pour & Spoon Foam",
                            Order = 4,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0001-000000000005"),
                            Description = "Optionally dust with cocoa powder or cinnamon and serve.",
                            DurationSeconds = 10,
                            Name = "Dust & Serve",
                            Order = 5,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0004-0001-000000000001"),
                            Description = "Grind 18g of coffee beans to a fine consistency.",
                            DurationSeconds = 30,
                            Name = "Grind Beans",
                            Order = 1,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0004-0001-000000000002"),
                            Description = "Extract a double shot of espresso (~36ml).",
                            DurationSeconds = 30,
                            Name = "Pull Espresso Shot",
                            Order = 2,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0004-0001-000000000003"),
                            Description = "Heat 180ml of fresh water to approximately 90°C.",
                            DurationSeconds = 60,
                            Name = "Heat Water",
                            Order = 3,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0004-0001-000000000004"),
                            Description = "Pour the hot water into the cup first, then add the espresso on top to preserve the crema.",
                            DurationSeconds = 15,
                            Name = "Combine & Serve",
                            Order = 4,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000001"),
                            Description = "Grind 18g of coffee beans to a fine consistency.",
                            DurationSeconds = 30,
                            Name = "Grind Beans",
                            Order = 1,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000002"),
                            Description = "Add 30ml of chocolate syrup or 2 tbsp of cocoa powder to the cup.",
                            DurationSeconds = 10,
                            Name = "Add Chocolate",
                            Order = 2,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000003"),
                            Description = "Extract a double shot of espresso (~36ml) directly over the chocolate.",
                            DurationSeconds = 30,
                            Name = "Pull Espresso Shot",
                            Order = 3,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000004"),
                            Description = "Stir the espresso and chocolate together until fully combined.",
                            DurationSeconds = 15,
                            Name = "Stir Base",
                            Order = 4,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000005"),
                            Description = "Steam 200ml of milk to 65°C with light foam.",
                            DurationSeconds = 45,
                            Name = "Steam Milk",
                            Order = 5,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000006"),
                            Description = "Pour steamed milk into the chocolate-espresso base, top with whipped cream.",
                            DurationSeconds = 20,
                            Name = "Pour & Top",
                            Order = 6,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0005-0001-000000000007"),
                            Description = "Drizzle chocolate syrup on top and serve immediately.",
                            DurationSeconds = 10,
                            Name = "Garnish & Serve",
                            Order = 7,
                            RecipeId = new Guid("b2c3d4e5-0002-0002-0002-000000000005")
                        });
                });

            modelBuilder.Entity("CoffeeMate.Infrastructure.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Collaborator", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.GuestToken", "GuestToken")
                        .WithMany()
                        .HasForeignKey("GuestTokenId");

                    b.HasOne("CoffeeMate.Domain.Entities.Session", "Session")
                        .WithMany("Collaborators")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany("Collaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuestToken");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.GuestToken", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.Session", "Session")
                        .WithMany("GuestTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.Coffee", "Coffee")
                        .WithOne("Recipe")
                        .HasForeignKey("CoffeeMate.Domain.Entities.Recipe", "CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Session", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.Coffee", "Coffee")
                        .WithMany("Sessions")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.SessionStep", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.Session", "Session")
                        .WithMany("SessionSteps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Step", b =>
                {
                    b.HasOne("CoffeeMate.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoffeeMate.Infrastructure.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Coffee", b =>
                {
                    b.Navigation("Recipe");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CoffeeMate.Domain.Entities.Session", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("GuestTokens");

                    b.Navigation("SessionSteps");
                });

            modelBuilder.Entity("CoffeeMate.Infrastructure.Data.AppUser", b =>
                {
                    b.Navigation("Collaborations");
                });
#pragma warning restore 612, 618
        }
    }
}
